#!/usr/bin/env bash
set -euo pipefail

INSTANCE="${BREV_INSTANCE_NAME:-$(hostname)}"
RUN_SLUG="${RUN_SLUG:-$INSTANCE}"
CONCURRENCY="${CONCURRENCY:-24}"
SAMPLE_SIZE="${SAMPLE_SIZE:-0}"
SEED="${SEED:-42}"
SHARD_COUNT="${SHARD_COUNT:-1}"
SHARD_INDEX="${SHARD_INDEX:-0}"
PYTHON_BIN="${PYTHON_BIN:-/tmp/rf100-runner-venv/bin/python}"
LOG_PATH="${LOG_PATH:-/tmp/rf100_brev_${INSTANCE}.log}"

REQUESTED_CONCURRENCY="$CONCURRENCY"
REQUESTED_SAMPLE_SIZE="$SAMPLE_SIZE"
REQUESTED_SEED="$SEED"
REQUESTED_SHARD_COUNT="$SHARD_COUNT"
REQUESTED_SHARD_INDEX="$SHARD_INDEX"
REQUESTED_RUN_ID="${RUN_ID:-}"

chmod 600 /tmp/rf100.env
source /tmp/rf100.env

CONCURRENCY="$REQUESTED_CONCURRENCY"
SAMPLE_SIZE="$REQUESTED_SAMPLE_SIZE"
SEED="$REQUESTED_SEED"
SHARD_COUNT="$REQUESTED_SHARD_COUNT"
SHARD_INDEX="$REQUESTED_SHARD_INDEX"
if [[ -n "$REQUESTED_RUN_ID" ]]; then
  RUN_ID="$REQUESTED_RUN_ID"
fi

"$PYTHON_BIN" -c 'import rf100vl' >/dev/null

if [[ -d /ephemeral && -w /ephemeral ]]; then
  DEFAULT_BENCHMARK_RUN_ROOT="/ephemeral/benchmark-runs"
  DEFAULT_RF100_VL_DATA_ROOT="/ephemeral/rf100-vl"
  DEFAULT_TMPDIR="/ephemeral/tmp"
else
  DEFAULT_BENCHMARK_RUN_ROOT="/tmp/benchmark-runs"
  DEFAULT_RF100_VL_DATA_ROOT="/tmp/rf100-vl"
  DEFAULT_TMPDIR="/tmp"
fi

export BENCHMARK_RUN_ROOT="${BENCHMARK_RUN_ROOT:-$DEFAULT_BENCHMARK_RUN_ROOT}"
export RF100_VL_DATA_ROOT="${RF100_VL_DATA_ROOT:-$DEFAULT_RF100_VL_DATA_ROOT}"
export RF100_VL_AUTO_DOWNLOAD="${RF100_VL_AUTO_DOWNLOAD:-1}"
export TMPDIR="${TMPDIR:-$DEFAULT_TMPDIR}"
export HF_HOME="${HF_HOME:-$BENCHMARK_RUN_ROOT/hf-home}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export BENCHMARK_NIM_BASE_URL="${BENCHMARK_NIM_BASE_URL:-http://127.0.0.1:8000/v1}"
export BREV_INSTANCE_NAME="$INSTANCE"
export CONCURRENCY
export SAMPLE_SIZE
export SEED
export SHARD_COUNT
export SHARD_INDEX
export RUN_ID="${RUN_ID:-bench-rf100-${RUN_SLUG}-$(date +%Y%m%d-%H%M%S)}"

ulimit -n 65535 || true
mkdir -p "$BENCHMARK_RUN_ROOT"
mkdir -p "$RF100_VL_DATA_ROOT" "$TMPDIR" "$HF_HOME" "$HF_HUB_CACHE" "$TRANSFORMERS_CACHE"
nohup "$PYTHON_BIN" /tmp/rf100_brev_runner.py > "$LOG_PATH" 2>&1 < /dev/null &
echo "started run_id=$RUN_ID concurrency=$CONCURRENCY shard=$SHARD_INDEX/$SHARD_COUNT log=$LOG_PATH"
